### ISSUE TITLE
Remote folders are downloaded in full site path

### ISSUE THREAD

**Issue by bernhardk4t** [readysitego/spgo#14]
I have a site with the following SPGo.json:

```
{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://tenant.sharepoint.com/sites/modernworkplace",
    "publishingScope": "Minor",
    "remoteFolders": [
        "/Style Library/custom",
        "/_catalogs/masterpage"
    ]
}
```

When starting "Populate local workspace" it will download the remote folders to a structure like this:
../src/sites/modernworkplace/Style Library/..." etc.
Also when modifying files locally or adding new ones and starting ""SPGo: Publish..." the files are not uploaded/published (although there is no error message).

As a workaround, after populating local workspace in Windows Explorer I moved the two remote folders directly underneath "src" and publishing worked again.

In another site collection on the same tenant everything works as described and the remote folders are created directly in "src".

One difference is that the site collection with the error has publishing feature activated and the other is a standard team site.

Regards, Bernhard

**Comment by sg-chrishasz** [comment]
Hello @bernhardk4t !

Can you tell me which version of SPGo you are currently running? I remember this was an issue with 0.10, but it is resolved in the latest version (0.10.2), available now on the Visual Studio Code Marketplace.

Please let me know if you still see this bug with the 0.10.2 release.

Thanks!
-Chris

**Comment by koltyakov** [comment]
It can be connected with SPPull, it happens when spFolder parameter is in the wrong case, different from those in SharePoint.
Created an issue in sppull project to fix this.

**Comment by koltyakov** [comment]
Should be fixed now. @sg-chrishasz, please check with `sppull` v 2.2.4

**Comment by bernhardk4t** [comment]
Thanks! I am using 0.10.2 and I still have this problem. You mention "spRootFolder": stupid question - I don't see this property in the configuration settings. What is it used for?
Will try again with the fix of @koltyakov when it is released.
BTW - great tool!

**Comment by koltyakov** [comment]
@bernhardk4t,

Those comments are mostly for  SPGo maintainers. They should know what it's about.
SPPull is a dev dependency with its interface. SPGo wraps the lib and provides its own properties layer.

Please stay tuned!

**Comment by sg-chrishasz** [comment]
@bernhardk4t -

I've upgraded to SPPull 2.2.5, which resolves this issue. I'm going to release SPGo 0.10.2 today after I finish testing.

Thanks,
Chris

**Comment by bernhardk4t** [comment]
Thanks! Works like a charm 👍
