### ISSUE TITLE
SPGo no longer working

### ISSUE THREAD

**Issue by JonMillerUK** [readysitego/spgo#27]
Since the latest update, I can't seem to use SPGo anymore. It doesn't seem to register in Code properly anymore. If I try to configure a new workspace I get the below. For existing projects, none of the commands are working. I've tried this in latest versions of Code and Code Insiders on both macOS and Windows but see same issue. 

I've tried reloading the extension as well as removing and reinstalling but to no avail. Any ideas what I can do to get this working again? It's an amazing extension and I feel lost without it!

<img width="1050" alt="screen shot 2018-02-26 at 11 42 54" src="https://user-images.githubusercontent.com/22253384/36668768-4016a8d0-1aea-11e8-81bd-c4235cffb765.png">

**Comment by sg-chrishasz** [comment]
Hello @JonMillerUK -

I'm going to try to reproduce this locally. In the meantime, can you see if there are any errors reported in the output window for spgo? It sounds like the extension is not initializing properly, but any additional details you can provide would help me resolve this quickly.

Thanks,
Chris

**Comment by sg-chrishasz** [comment]
@JonMillerUK - Can you also verify that you SPGo.json file is properly formatted and without error? I have found that VSCode will prevent SPGo from loading and registering any commands when there is a format error with the JSON data.

You can use a tool like [JSONLint](https://jsonlint.com/) to validate your config file.

Thanks,
Chris

**Comment by JonMillerUK** [comment]
Thanks for reply. 

Nothing is being reported at all in the Output window and the JSON is ok. I am seeing this error even if I try to setup a new workspace - as you say, it doesn't seem to initialise the extension. 

I have a different Win10 machine which tried updated version of the extension on and that still works - only difference there is that VS Code isn't the latest version.

**Comment by sg-chrishasz** [comment]
The VSCode version may be the key here! Both VSCode and TypeScript were rev'd recently and I know I spent about 2 hours trying to sort out dependencies and transient package errors in my local environment. I suspect that this is the root cause of your errors (and probably other's who have not reported this).

I'm going to build SPGo 1.2.1 against VSCode 1.20 and TypeScript 2.7.2 and make sure that all the dependencies are playing nice. I expect to release this update today, so bear with me!

Thanks,
Chris

**Comment by JonMillerUK** [comment]
That's awesome. Thank you. I just found an old VM with VS code 1.18.0 and SPGo worked perfectly in there.

I then let it update to 1.20.0 and now doesn't work so does look like the versioning is the issue.

Thanks again - this extension is just awesome! I use it for everything. So nice to be able to do SP stuff natively on my Mac!

**Comment by sg-chrishasz** [comment]
Hello @JonMillerUK 

I've submitted SPGo 1.2.1 to the VSCode marketplace. This version is compiled against Typescript 2.7.2 and requires VSCode 1.20.0 or greater. Can you update and confirm that your issues are resolved?

Thanks,
Chris

**Comment by JonMillerUK** [comment]
Hi @sg-chrishasz, unfortunately it still isn't working for me. Did you manage to get 1.2.1 to work in VSCode 1.20.0?

**Comment by bernhardk4t** [comment]
Hi @sg-chrishasz same here - as soon as it works I'll try the German cloud connectivity :-)

**Comment by dhumel** [comment]
hello everyone, today I received the same issue that @JonMillerUK had. I worked yesterday all day, but today any of commands did work, I tried uninstall and install again but nothing works current version is 1.2.1  just for know

**Comment by sg-chrishasz** [comment]
Hello Everyone-

Sorry about the ongoing challenges. I created a new VM this morning and am able to reproduce the issue, but I have not yet found a root cause. I'm going to work on this today and get a fix out as soon as possible. I appreciate your patience with this (annoying) issue!

-Chris

**Comment by sg-chrishasz** [comment]
**Update**- I have found the root cause of the issue: I have a packaging issue with one of my dependencies. In a recent update, it has been configured specifically as a dev dependency, but that prevents it from being packaged with SPGo when deploying. This is why it worked in my local environment and not when I packaged the extension for the marketplace.

I have contacted the package owner via GitHub and will update this issue when I hear back.

Note: the VSCode debugger (Help-> Toggle Developer tools) was instrumental in finding the root cause here. This was a lifesaver!

Thanks all, for your patience here!
-Chris

**Comment by sg-chrishasz** [comment]
Hello Everyone-

I'm happy to say that with some help from the community (@koltyakov, @s-KaiNet), we have resolved the issue. The root cause was an error with how NPM treats transient dependencies in the most recent versions.

I have published SPGo 1.2.2 to the marketplace which should resolve this issue. Please test and reopen if there are any persistent issues.

Thank you all for your patience with this!

-Chris
